### Ex1: Tạo matrix

In [0]:
x <- c(round(runif(3,1,10),0))
y <- c(round(runif(3,1,10),0))
z <- c(round(runif(3,1,10),0))

In [0]:
v1 <- c(x,y,z)

In [0]:
matrix_1 <- matrix(v1, nrow = 3, ncol = 3, byrow = TRUE, dimnames = list(c("r1","r2", "r3"),c("c1","c2", "c3")))
print(matrix_1)
print(paste("Class:",class(matrix_1)))

   c1 c2 c3
r1  2  2  3
r2  6  7  7
r3  3  9  6
[1] "Class: matrix"


In [0]:
#Ma tra chuyen vi cua matrix_1
t_matrix_1 <- t(matrix_1)
print(t_matrix_1)

   r1 r2 r3
c1  7  8  5
c2  7  8 10
c3  2  8  9


### Ex2: Tạo và tính toán trên matrix

In [0]:
#Tao matrix_b 4x3
B <- matrix(c(1:12), nrow = 4, ncol = 3, dimnames = list(c("a","b", "c", "d"),c("x","y", "z")))
print(B)

  x y  z
a 1 5  9
b 2 6 10
c 3 7 11
d 4 8 12


In [0]:
#tao ma tran chuyen vi cua matrix_b
t_B <- t(B)
print(t_B)

  a  b  c  d
x 1  2  3  4
y 5  6  7  8
z 9 10 11 12


In [0]:
#tao ma tran con subB
subB <- matrix_b[2:dim(B)[1],1:3]
print("Matrix sub of B:")
print(subB)

[1] "Matrix sub of B:"
  x y  z
b 2 6 10
c 3 7 11
d 4 8 12


In [0]:
#Tao matrix A 3x3, cac gia tri la so nguyen 1->9, xep theo dong
A <- matrix(c(1:9), nrow = 3, ncol = 3, dimnames = list(c("a","b", "c"),c("x","y", "z")))
print(A)

  x y z
a 1 4 7
b 2 5 8
c 3 6 9


In [0]:
#3A
A3 <- A*3
print("3*A = ")
print(A3)

[1] "3*A = "
  x  y  z
a 3 12 21
b 6 15 24
c 9 18 27


In [0]:
#A + subB
A_plus_subB <- A + subB
print("A + subB = ")
print(A_plus_subB)

[1] "A + subB = "
  x  y  z
a 3 10 17
b 5 12 19
c 7 14 21


In [0]:
#A - subB
A_minus_subB <- A - subB
print("A - subB = ")
print(A_minus_subB)

[1] "A - subB = "
   x  y  z
a -1 -2 -3
b -1 -2 -3
c -1 -2 -3


### Ex3: Tạo và tính toán trên matrix

In [2]:
n <- as.integer(readline(prompt = "Input n : "))

Input n : 4


In [3]:
#Tao matrix A1 nxn
A1 <- matrix(round(runif(n*n, min = 1, max = n*n)), n, n) # dung so nguyen ngau nhien
print("Matrix A1:")
print(A1)

[1] "Matrix A1:"
     [,1] [,2] [,3] [,4]
[1,]   10    5   10    5
[2,]   10    8   10    2
[3,]   10   13    2    1
[4,]    2    9   12    4


In [4]:
m <- as.integer(readline(prompt = "Input m :"))

Input m :3


In [5]:
#Tao matrix A2 co mxn phan tu so nguyen ngau nhien
A2<- matrix(round(runif(n*m, min = 1, max = n*m)), n, m)
print("Matrix A2:")
print(A2)

[1] "Matrix A2:"
     [,1] [,2] [,3]
[1,]    8    5   12
[2,]   11    1   10
[3,]    7    3    1
[4,]    2    1    9


In [8]:
#Tinh M biet A1*M = A2
# Day la bai toan A1* M = A va khong phai luc nao no cung co nghiem khi tao cac gia tri cho A1, A2. De dam bao ta nen dung so nguyen
# Co co sua lai cach tao cac gia tri so nguyen cho ma tran A1, A2 o tren
M <- solve(A1,A2)
print(M)

           [,1]        [,2]       [,3]
[1,]  0.9421875  0.23437500  0.3703125
[2,] -0.1781250  0.01041667 -0.3635417
[3,]  0.5359375 -0.41145833  0.8598958
[4,] -1.1781250  1.34375000  0.3031250


In [0]:
# example(solve)

### Ex4: Tính toán trên Array

In [0]:
m1 <- matrix(c(1:9), nrow = 3, ncol = 3, byrow = TRUE)
m2 <- matrix(c(10:18), nrow = 3, ncol = 3, byrow = TRUE)

In [0]:
A3 <- array(c(m1,m2), dim = c(3,3,2), dimnames = list(c("r1","r2","r3"), c("cl","c2","c3"),c("matrix1","matrix2")))
print(A3)

, , matrix1

   cl c2 c3
r1  1  2  3
r2  4  5  6
r3  7  8  9

, , matrix2

   cl c2 c3
r1 10 11 12
r2 13 14 15
r3 16 17 18



In [0]:
#In tong theo dong cua tat ca cac ma tran
print("Tong theo dong cua tat ca cac ma tran:")
print(apply(A3, c(1),sum))
print("Tong theo cot cua tat ca cac ma tran:")
print(apply(A3, c(2),sum))
print("Tong theo cac ma tran:")
print(apply(A3, c(3),sum))
print("Tong dong 1 cua matrix 1:")
print(sum(A3[1,,1]))
print("Tich cot 2 cua matrix 2:")
print(prod(A3[,2,2]))

[1] "Tong theo dong cua tat ca cac ma tran:"
r1 r2 r3 
39 57 75 
[1] "Tong theo cot cua tat ca cac ma tran:"
cl c2 c3 
51 57 63 
[1] "Tong theo cac ma tran:"
matrix1 matrix2 
     45     126 
[1] "Tong dong 1 cua matrix 1:"
[1] 6
[1] "Tich cot 2 cua matrix 2:"
[1] 2618


### Ex5: Tạo và tính toán trên array

In [0]:
v <- c()
i <-1 
while (i<= 50){
    x = floor(runif(1, min= 5, max = 50))
    if (x%%2 == 0){
        v[i] <- x
        i <- i + 1
    }
}
print(v)

 [1] 10 44 24 48 18 14 44 20 40 16 24 16 40 44 32 24 16 44 34 22 34 20 18 42 44
[26] 46  8 28 32 30 22 18 14 32 28 14 16 42 38 40 24 22  6 24 22  6 30 26 36  6


In [0]:
#Tao array gom 2 matrix 5x5
A4 <- array(v, dim = c(5,5,2))
print("Array A4:")
print(A4)

[1] "Array A4:"
, , 1

     [,1] [,2] [,3] [,4] [,5]
[1,]   10   14   24   24   34
[2,]   44   44   16   16   20
[3,]   24   20   40   44   18
[4,]   48   40   44   34   42
[5,]   18   16   32   22   44

, , 2

     [,1] [,2] [,3] [,4] [,5]
[1,]   46   22   14   24    6
[2,]    8   18   16   22   30
[3,]   28   14   42    6   26
[4,]   32   32   38   24   36
[5,]   30   28   40   22    6



In [0]:
no_row <- dim(A4)[1]
no_col <- dim(A4)[2]
no_matrix <- dim(A4)[3]
m <- 1
r <- 1
c <- 1
tong <- 0
while(m <= no_matrix){
    r <- 1
    while (r <= no_row){
        c <- 1
        while (c <= no_col){
            if(A4[r,c,m]%%2 == 0 & A4[r,c,m]%%3 == 0 & A4[r,c,m]%%6 == 0){
                print(paste("A4[",r,",",c,",",m,"] =", A4[r,c,m]))
                tong <- tong + A4[r,c,m]
            }
            c <- c +1
        }
       r <- r + 1 
    }
   m <- m + 1 
}
print(paste("Tong =", tong))

[1] "A4[ 1 , 3 , 1 ] = 24"
[1] "A4[ 1 , 4 , 1 ] = 24"
[1] "A4[ 3 , 1 , 1 ] = 24"
[1] "A4[ 3 , 5 , 1 ] = 18"
[1] "A4[ 4 , 1 , 1 ] = 48"
[1] "A4[ 4 , 5 , 1 ] = 42"
[1] "A4[ 5 , 1 , 1 ] = 18"
[1] "A4[ 1 , 4 , 2 ] = 24"
[1] "A4[ 1 , 5 , 2 ] = 6"
[1] "A4[ 2 , 2 , 2 ] = 18"
[1] "A4[ 2 , 5 , 2 ] = 30"
[1] "A4[ 3 , 3 , 2 ] = 42"
[1] "A4[ 3 , 4 , 2 ] = 6"
[1] "A4[ 4 , 4 , 2 ] = 24"
[1] "A4[ 4 , 5 , 2 ] = 36"
[1] "A4[ 5 , 1 , 2 ] = 30"
[1] "A4[ 5 , 5 , 2 ] = 6"
[1] "Tong = 420"


### Ex6: Tạo và tính toán trên List

In [0]:
p<- c(2,7,8)
q<- c("A","B","C")
x <- list(p,q)

In [0]:
print("List x :")
print(x)

[1] "List x :"
[[1]]
[1] 2 7 8

[[2]]
[1] "A" "B" "C"



In [0]:
#In gia tri cua x tai vi tri thu 2
print(paste("Gia tri cua x tai vtri thu 2:",x[2]))
#In gia tri cua phan tu thu 2 cua vector thu 2 trong list
print(paste("Gia tri cua phan tu thu 2 cua vector thu 2:",x[[2]][2]))
#Thay the phan tu thu 2 cua vector thu 2 trong list bang K
x[[2]][2] <- "K"
print("List after changes:")
print(x)

[1] "Gia tri cua x tai vtri thu 2: c(\"A\", \"B\", \"C\")"
[1] "Gia tri cua phan tu thu 2 cua vector thu 2: B"
[1] "List after changes:"
[[1]]
[1] 2 7 8

[[2]]
[1] "A" "K" "C"



In [0]:
#Cho vector c(1,3,4), them vao list x
t <- c(1,3,4)
x[length(x)+1] <- list(t)

In [0]:
print("List after adding t:")
print(x)

[1] "List after adding t:"
[[1]]
[1] 2 7 8

[[2]]
[1] "A" "K" "C"

[[3]]
[1] 1 3 4



In [0]:
#Tao list a
a <- list("x"=5, "y"=10, "z"=15)
print("List a:")
print(a)

[1] "List a:"
$x
[1] 5

$y
[1] 10

$z
[1] 15



In [0]:
#TOng cac phan tu trong list
print(paste("Sum of list elements:",sum(unlist(a))))

[1] "Sum of list elements: 30"


In [0]:
#Tao newlist
newlist <- list(a=1:10,b="Good morning", c= "Hi")

In [0]:
#Cong them 1 vao cac phan tu cua element a trong newlist
newlist$a <- newlist$a + 1

In [0]:
print("Newlist after:")
print(newlist)

[1] "Newlist after:"
$a
 [1]  2  3  4  5  6  7  8  9 10 11

$b
[1] "Good morning"

$c
[1] "Hi"



### Ex7: Tạo và tính toán trên list

In [0]:
#Tao 3 vector
year <- c(2008:2018)
month <- c(1:12)
day <- c(1:31)

In [0]:
#Tao list chua 3 vector year, month, day
year_month_day.list <- list("year" = year, "month"=month, "day"=day)
print("List after creating:")
print(year_month_day.list)

[1] "List after creating:"
$year
 [1] 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018

$month
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

$day
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31



In [0]:
#Cap nhat year trong list thanh c(2010:2020)
year_month_day.list$year <- c(2010:2020)
print("List after updating:")
print(year_month_day.list)

[1] "List after updating:"
$year
 [1] 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020

$month
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

$day
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31



In [0]:
#Bo nam dau tien trong year cua list
year_month_day.list$year <- year_month_day.list$year[-1]

In [0]:
print("List after dropping first year:")
print(year_month_day.list)

[1] "List after dropping first year:"
$year
 [1] 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020

$month
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

$day
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31



In [0]:
#Tao vector x
x <- c(1,3,4,7,11,18,19)
x.list <- list("x*2"=x*2, "x/2"=x/2, "sqrt(x)"=sqrt(x))

In [0]:
print(x.list)

$`x*2`
[1]  2  6  8 14 22 36 38

$`x/2`
[1] 0.5 1.5 2.0 3.5 5.5 9.0 9.5

$`sqrt(x)`
[1] 1.000000 1.732051 2.000000 2.645751 3.316625 4.242641 4.358899



In [0]:
#in 3 phan tu giua cua sqrt(x)
mid <- floor(length(x.list$`sqrt(x)`)/2)
print(paste("In 3 phan tu giua cua sqrt(x):", toString(x.list$`sqrt(x)`[mid:(mid+2)])))

[1] "In 3 phan tu giua cua sqrt(x): 2, 2.64575131106459, 3.3166247903554"


In [0]:
#Tao list moi chua 2 list x va year_month_day
new.list <- c(year_month_day.list, x.list)
print("new list:")
print(new.list)

[1] "new list:"
$year
 [1] 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020

$month
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

$day
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31

$`x*2`
[1]  2  6  8 14 22 36 38

$`x/2`
[1] 0.5 1.5 2.0 3.5 5.5 9.0 9.5

$`sqrt(x)`
[1] 1.000000 1.732051 2.000000 2.645751 3.316625 4.242641 4.358899



In [0]:
#tao list con chua year, x*2, day tu tu newlist
sub_new.list <- new.list[c("year","x*2","day")]
print("Sub new list:")
print(sub_new.list)

[1] "Sub new list:"
$year
 [1] 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020

$`x*2`
[1]  2  6  8 14 22 36 38

$day
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31



In [0]:
#chieu dai cua element x*2 trong sub_new list
len_element2 <- length(sub_new.list$`x*2`)
print(paste("chieu dai cua element x*2:",len_element2))

[1] "chieu dai cua element x*2: 7"


In [0]:
#In gia tri phan tu cuoi cung trong year
print(paste("Gia tri cua phan tu cuoi cung trong element year:",sub_new.list$year[length(sub_new.list$year)]))

[1] "Gia tri cua phan tu cuoi cung trong element year: 2020"


### Ex8: Tạo và tính toán trên list

In [0]:
# tao list y
y <- list(c("a","b","c"),c(1,2,3),10)
y

[[1]]
[1] "a" "b" "c"

[[2]]
[1] 1 2 3

[[3]]
[1] 10

In [0]:
#dat ten cho cac phan tu cua list
names(y) <- c("one","two","three")
y

$one
[1] "a" "b" "c"

$two
[1] 1 2 3

$three
[1] 10

In [0]:
#Chieu dai cua tung phan tu trong list
print(paste("Chieu dai cua one, two, three: ",length(y$one),",", length(y$two),",", length(y$three)))

[1] "Chieu dai cua one, two, three:  3 , 3 , 1"


In [0]:
#Tao list z
z<-list(c("a","b","c"), c(1,3,5,7), TRUE)
z

[[1]]
[1] "a" "b" "c"

[[2]]
[1] 1 3 5 7

[[3]]
[1] TRUE

In [0]:
#Tao list moi chi co cac phan tu trong y
t1 <- setdiff(y,z)
t1

[[1]]
[1] 1 2 3

[[2]]
[1] 10

In [0]:
#Tao list moi chi co cac phan tu trong z
t2 <- setdiff(z,y)
t2

[[1]]
[1] 1 3 5 7

[[2]]
[1] TRUE